[package]
name = "tg_channel_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
thiserror = "1.0.61"
teloxide = { version = "0.12.1", features = [
    "macros",
    "ctrlc_handler",
    "rustls",
] }
